name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.0

      - name: Install dependencies
        run: npm install

      - name: Run type checking
        run: npm run typecheck

      - name: Run linting
        run: npm run lint
